using System.Globalization;
using System.Text;
using FinanceAi.Domain.Entities;

namespace FinanceAi.Infrastructure.Messaging;

/// <summary>
/// The native-speaker review pack (slice 21): every system template in both languages side by side, the placeholder
/// glossary, and the checklist the reviewer answers per template. Rendered by <c>FinanceAi.Migrator review-pack</c>
/// from the same <see cref="SystemTemplates.All"/> the product seeds — never a copy that can drift.
/// </summary>
public static class ReviewPack
{
    public static string Render(DateOnly asOf)
    {
        var sb = new StringBuilder();
        sb.AppendLine(CultureInfo.InvariantCulture, $"# Arabic review pack — system templates as of {asOf:yyyy-MM-dd}");
        sb.AppendLine();
        sb.AppendLine("Generated by `FinanceAi.Migrator review-pack` from `SystemTemplates.All` — do not edit by hand; re-generate after a change.");
        sb.AppendLine();
        sb.AppendLine("**For the reviewer (a native speaker of Jordanian Arabic who writes business correspondence):** for every Arabic template answer the checklist; for every English one confirm the register matches its Arabic sibling. Placeholders (`{{…}}`) are filled by the system — judge the words around them. Money and dates are inserted already formatted (`1,250.500 د.أ` / `2026-09-11`), so do not translate them.");
        sb.AppendLine();
        sb.AppendLine("## Checklist per template");
        sb.AppendLine();
        sb.AppendLine("| # | Question | Answer |");
        sb.AppendLine("|---|----------|--------|");
        sb.AppendLine("| 1 | Register: is the Arabic Modern Standard, suitable for business email, without dialect where the tone is `firm`/`final`? | |");
        sb.AppendLine("| 2 | Tone matches the label (`polite`, `neutral`, `firm`, `final`) and is not harsher than the English sibling? | |");
        sb.AppendLine("| 3 | Nothing threatens legal action or names a penalty (AI/product rule: escalation is a human decision, never a template)? | |");
        sb.AppendLine("| 4 | Gender-neutral or correctly dual-form address for an unknown contact? | |");
        sb.AppendLine("| 5 | Reads naturally when a placeholder is a company name rather than a person? | |");
        sb.AppendLine("| 6 | WhatsApp variants: short enough for a phone screen, no email formalities? | |");
        sb.AppendLine("| 7 | Any wording a Jordanian customer would find unusual, foreign or machine-like? Suggest the replacement. | |");
        sb.AppendLine();
        sb.AppendLine("## Placeholders");
        sb.AppendLine();
        sb.AppendLine("| Placeholder | Type | Meaning |");
        sb.AppendLine("|-------------|------|---------|");
        foreach (var p in Placeholders.All)
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"| `{{{{{p.Name}}}}}` | {p.Type} | {p.Description} |");
        }

        sb.AppendLine();
        sb.AppendLine("## Templates");
        foreach (var group in SystemTemplates.All.GroupBy(t => (t.Key, t.Channel)).OrderBy(g => g.Key.Key, StringComparer.Ordinal).ThenBy(g => g.Key.Channel, StringComparer.Ordinal))
        {
            var ar = group.FirstOrDefault(t => t.Language == "ar");
            var en = group.FirstOrDefault(t => t.Language == "en");
            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture, $"### `{group.Key.Key}` · {group.Key.Channel} · tone `{(ar ?? en)?.Tone}`");
            sb.AppendLine();
            sb.AppendLine("<table><tr><th style=\"width:50%\">العربية</th><th style=\"width:50%\">English</th></tr><tr>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<td dir=\"rtl\" style=\"vertical-align:top\">{Cell(ar)}</td>");
            sb.AppendLine(CultureInfo.InvariantCulture, $"<td dir=\"ltr\" style=\"vertical-align:top\">{Cell(en)}</td>");
            sb.AppendLine("</tr></table>");
            sb.AppendLine();
            sb.AppendLine("Reviewer notes:");
            sb.AppendLine();
            sb.AppendLine("> ");
        }

        sb.AppendLine();
        sb.AppendLine("## The daily briefing narrative");
        sb.AppendLine();
        sb.AppendLine("The narrative is written by the model from the day's figures (prompt `services/ai/prompts/daily_briefing/v1.md`, Arabic and English generated separately). Review three real briefings from the pilot tenant (Today screen → the AI summary card) against the same checklist, plus: does the prose ever restate a number differently from the figure beside it? (The guard should make that impossible — say if you see it.)");
        return sb.ToString();
    }

    private static string Cell(SystemTemplates.Seed? seed)
    {
        if (seed is null) return "<em>missing</em>";
        var body = System.Net.WebUtility.HtmlEncode(seed.Body).Replace("\n", "<br>", StringComparison.Ordinal);
        return seed.Subject is null ? body : $"<strong>{System.Net.WebUtility.HtmlEncode(seed.Subject)}</strong><br><br>{body}";
    }
}
