using FinanceAi.Domain.Abstractions;

namespace FinanceAi.Domain.Entities;

public enum CustomerStatus { Active, Inactive }

public enum RiskFlag { None, Watch, HighRisk, Legal }

/// <summary>
/// The party the tenant chases (doc 04 §5.1). Names are authored per language, not translated
/// (ADR-0005); at least one is required, and the database enforces that too.
/// <para>
/// There is no balance on this entity, and there never will be: balances are derived from invoices
/// and payments (FIN-10, FIN-15). The credit limit is the only money here, and it is a stored
/// figure, not a computed one.
/// </para>
/// </summary>
public sealed class Customer : ITenantScoped
{
    public Guid Id { get; set; } = Guid.CreateVersion7();
    public Guid TenantId { get; set; }

    /// <summary>The tenant's own customer code; unique per tenant among live rows, case-insensitively.</summary>
    public string? Code { get; set; }

    public string? NameAr { get; set; }
    public string? NameEn { get; set; }
    public string? LegalName { get; set; }
    public string? TaxRegistrationNo { get; set; }

    /// <summary>The language messages to this customer are written in (UI-14): 'ar' or 'en'.</summary>
    public string PreferredLanguage { get; set; } = "ar";

    /// <summary>FIN-72. Default 30; an invoice may override.</summary>
    public int PaymentTermsDays { get; set; } = 30;

    /// <summary>DM-09: a money column always travels with its currency. Both null, or neither.</summary>
    public decimal? CreditLimitAmount { get; set; }

    public string? CreditLimitCurrency { get; set; }

    public string DefaultCurrency { get; set; } = "JOD";
    public RiskFlag RiskFlag { get; set; } = RiskFlag.None;
    public CustomerStatus Status { get; set; } = CustomerStatus.Active;

    /// <summary>Maintained by a later slice's job; advisory only.</summary>
    public int BrokenPromiseCount12m { get; set; }

    public int BouncedChequeCount12m { get; set; }
    public string? Notes { get; set; }

    /// <summary>Generated by the database from both names via <c>app_normalize_arabic</c> (DM-20). Read-only.</summary>
    public string NormalizedName { get; private set; } = string.Empty;

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public Guid? CreatedBy { get; set; }
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;
    public Guid? UpdatedBy { get; set; }
    public long RowVersion { get; set; } = 1;

    /// <summary>DM-08: customers are soft-deleted, never removed. Financial history survives.</summary>
    public DateTimeOffset? DeletedAt { get; set; }

    /// <summary>DM-21 (slice 23): set on the merged-away row, which is retained; the survivor's id.</summary>
    public Guid? MergedIntoId { get; set; }

    public DateTimeOffset? MergedAt { get; set; }

    public bool HasAName => !string.IsNullOrWhiteSpace(this.NameAr) || !string.IsNullOrWhiteSpace(this.NameEn);
}

/// <summary>A person at the customer we may write to (doc 04 §5.1). Exactly one primary per customer.</summary>
public sealed class CustomerContact : ITenantScoped
{
    public Guid Id { get; set; } = Guid.CreateVersion7();
    public Guid TenantId { get; set; }
    public Guid CustomerId { get; set; }
    public required string Name { get; set; }
    public string? RoleTitle { get; set; }
    public string? Email { get; set; }

    /// <summary>E.164, e.g. +9627…; the only form WhatsApp click-to-chat accepts (ADR-0004).</summary>
    public string? PhoneE164 { get; set; }

    public bool IsPrimary { get; set; }
    public bool IsBilling { get; set; }
    public string? PreferredLanguage { get; set; }

    /// <summary>Slice 25: the MTA bounced this address; sends to it are refused (`contact_email_bounced`) until the email is edited.</summary>
    public DateTimeOffset? BouncedAt { get; set; }

    public string? BounceReason { get; set; }

    /// <summary>Slice 31 (SEC-93): the personal data was anonymized in place; the row is kept for the messages that reference it and is read-only from here.</summary>
    public DateTimeOffset? ErasedAt { get; set; }

    public Guid? ErasedBy { get; set; }
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;
    public DateTimeOffset UpdatedAt { get; set; } = DateTimeOffset.UtcNow;
    public long RowVersion { get; set; } = 1;

    public const string ErasedName = "Erased contact";
}

/// <summary>
/// Doc 10 §2.4: a customer with an open balance cannot be deleted. Invoices do not exist until
/// slice 3, so the guard is an interface with a stub now and a real query then; the endpoint and
/// its 422 test do not change when that happens.
/// </summary>
public interface ICustomerBalanceGuard
{
    Task<bool> HasOpenBalanceAsync(Guid customerId, CancellationToken ct = default);
}

public sealed class NoInvoicesYetBalanceGuard : ICustomerBalanceGuard
{
    public Task<bool> HasOpenBalanceAsync(Guid customerId, CancellationToken ct = default) => Task.FromResult(false);
}
